# Basis-Image wählen (zu ergänzen)
FROM

# Arbeitsverzeichnis setzen
WORKDIR

# Kopieren Sie die Webseiten-Dateien in den Container (zu ergänzen)
COPY

# Port deklarieren (zu ergänzen)
EXPOSE

# Start-Befehl ist bereits im nginx-Image definiert
